Add a method for adding nodes to the network
NordicSemiconductor/Android-nRF-Mesh-Library pull request #366
Opened 2020-12-15 15:05 UTC by saty9

Currently there is not a way to add nodes to the network as there is in the [ios version](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/f9a09aafe091e9597b99c6d615278a681d79561c/nRFMeshProvision/Classes/Mesh%20API/MeshNetwork%2BNodes.swift#L127-L156). This adds a method that:
* errors if the address of the node being added conflicts with pre-existing nodes
* updates an existing node if their uuids match
* appends the node to the end of the list if there were no matches

This is useful in the case where you are interacting with a network that contains already provisioned nodes.

2021-01-19 14:13 UTC, roshanrajaratnam requested changes
Thanks for this @saty9, I see that this implementation is based on what's on the iOS version of the library. However there are couple of things that's missed here. We should ensure the node has a NetworkKey and also the same network key (both key and index should match) exists in the Network.

2021-01-26 10:28 UTC, saty9 commented
@roshanrajaratnam I have added a bit to check if there is a matching key index is that sufficient or do I need to change node keys to also contain the actual key instead of just an index.

2021-12-13 10:31 UTC, roshanrajaratnam requested changes
@saty9 thank you for taking your time  on the PR and really sorry for the delayed reply been a bit busy with some other projects. Good that you are checking if the keys are in use using the index. However the library does not allow duplicate keys. I guess you have to check for both Network keys and application keys. and there are two utility methods for this that you could use. https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/e03b1eba6cf4d7bb41b1fa36d3ce8055e8df4208/mesh/src/main/java/no/nordicsemi/android/mesh/BaseMeshNetwork.java#L158

https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/e03b1eba6cf4d7bb41b1fa36d3ce8055e8df4208/mesh/src/main/java/no/nordicsemi/android/mesh/BaseMeshNetwork.java#L505

Everything else looks fine.

2021-12-13 10:38 UTC, merged

2021-12-13 10:50 UTC, roshanrajaratnam commented
@saty9 FYI adds some minor improvements